# tests/test_matchroom.py
import json

import pytest
from fastapi.websockets import WebSocketDisconnect


def test_arcade_match_lifecycle(client):
    p1_params = "identity_type=anonymous&player_identifier=guest123&display_name=CasualRonnie"
    with client.websocket_connect(f"/ws/room/table_one?{p1_params}") as ws1:
        # Consumes: Initial connection frame for Player 1
        _ = ws1.receive_text()

        p2_params = "identity_type=anonymous&player_identifier=guest789&display_name=CasualJudd"
        with client.websocket_connect(f"/ws/room/table_one?{p2_params}") as ws2:
            # Consumes: Initial connection frame for Player 2
            _ = ws2.receive_text()

            # Flush: Player 1 now consumes the broadcast frame generated by Player 2 joining
            _ = ws1.receive_text()

            # Now both buffers are clean. Simulate Player 1 potting a Black (7 points)
            ws1.send_text(json.dumps({"action": "pot", "points": 7}))

            # Read the absolute fresh broadcast frames
            broadcast_p1 = json.loads(ws1.receive_text())
            assert broadcast_p1["scores"]["anon_guest123"] == 7
            assert broadcast_p1["current_break"] == 7


def test_successful_tournament_handshake(client, mock_rackup_client):
    params = "identity_type=verified&player_identifier=42&display_name=RonnieO&match_id=999"
    with client.websocket_connect(f"/ws/room/tournament_table?{params}") as ws:
        data = json.loads(ws.receive_text())
        assert data["match_id"] == "999"
        assert data["current_turn"] == "user_42"

    # This will now pass perfectly because the module patch path is aligned
    mock_rackup_client.fetch_tournament_match.assert_called_once_with("999")


def test_unauthorized_player_is_rejected(client):
    # User 99 is an invalid player for tournament match 999
    invalid_params = "identity_type=verified&player_identifier=99&display_name=Impostor&match_id=999"

    # Assert that the gateway strictly raises a WebSocketDisconnect close frame
    with pytest.raises(WebSocketDisconnect) as exc_info:
        with client.websocket_connect(f"/ws/room/tournament_table?{invalid_params}"):
            pass

    # Verify the handshake was dropped with your policy violation code (1008)
    assert exc_info.value.code == 1008
