# tests/test_matchroom.py
import json


def test_arcade_match_lifecycle(client):
    p1_params = "match_id=table_one&identity_type=anonymous&player_id=guest123&display_name=CasualRonnie"
    with client.websocket_connect(f"/ws/room/?{p1_params}") as ws1:
        # Consumes: Initial connection frame for Player 1
        _ = ws1.receive_text()

        p2_params = "match_id=table_one&identity_type=anonymous&player_id=guest789&display_name=CasualJudd"
        with client.websocket_connect(f"/ws/room/?{p2_params}") as ws2:
            # Consumes: Initial connection frame for Player 2
            _ = ws2.receive_text()

            # Flush: Player 1 now consumes the broadcast frame generated by Player 2 joining
            _ = ws1.receive_text()

            # Now both buffers are clean. Simulate Player 1 potting a Black (7 points)
            ws1.send_text(json.dumps({"action": "pot", "points": 7}))

            # Read the absolute fresh broadcast frames
            broadcast_p1 = json.loads(ws1.receive_text())
            assert broadcast_p1["scores"]["anon_guest123"] == 7
            assert broadcast_p1["current_break"] == 7


def test_successful_tournament_handshake(client, mock_rackup_client):
    params = "identity_type=verified&player_id=42&display_name=RonnieO&match_id=999"
    with client.websocket_connect(f"/ws/room/?{params}") as ws:
        data = json.loads(ws.receive_text())
        assert data["match_id"] == "999"
        assert data["current_turn"] == "user_42"

    # Verification is currently disabled in websocket.py
    mock_rackup_client.fetch_tournament_match.assert_not_called()


def test_unauthorized_player_is_currently_allowed_when_verification_disabled(client):
    # User 99 is currently accepted because verification is disabled.
    invalid_params = "identity_type=verified&player_id=99&display_name=Impostor&match_id=999"

    with client.websocket_connect(f"/ws/room/?{invalid_params}") as ws:
        data = json.loads(ws.receive_text())
        assert data["match_id"] == "999"
        assert data["current_turn"] == "user_99"


def test_reconnect_restores_existing_match_state(client):
    p1_params = "match_id=reconnect_table&identity_type=anonymous&player_id=guest123&display_name=CasualRonnie"

    with client.websocket_connect(f"/ws/room/?{p1_params}") as ws1:
        _ = ws1.receive_text()
        ws1.send_text(json.dumps({"action": "pot", "points": 7}))
        snapshot = json.loads(ws1.receive_text())
        assert snapshot["scores"]["anon_guest123"] == 7

    with client.websocket_connect(f"/ws/room/?{p1_params}") as ws1_reconnected:
        reconnect_snapshot = json.loads(ws1_reconnected.receive_text())
        assert reconnect_snapshot["scores"]["anon_guest123"] == 7


def test_invalid_action_returns_validation_error(client):
    params = "match_id=validation_table&identity_type=anonymous&player_id=guestA&display_name=Breaker"
    with client.websocket_connect(f"/ws/room/?{params}") as ws:
        _ = ws.receive_text()
        ws.send_text(json.dumps({"action": "invalid_action"}))
        err = json.loads(ws.receive_text())
        assert "Unsupported action" in err["error"]


def test_turn_enforcement_blocks_out_of_turn_actions(client):
    p1_params = "match_id=turn_table&identity_type=anonymous&player_id=guest123&display_name=CasualRonnie"
    p2_params = "match_id=turn_table&identity_type=anonymous&player_id=guest789&display_name=CasualJudd"

    with client.websocket_connect(f"/ws/room/?{p1_params}") as ws1:
        _ = ws1.receive_text()

        with client.websocket_connect(f"/ws/room/?{p2_params}") as ws2:
            _ = ws2.receive_text()
            _ = ws1.receive_text()

            ws2.send_text(json.dumps({"action": "pot", "points": 7}))
            err = json.loads(ws2.receive_text())
            assert err["error"] == "It is not your turn to score."


def test_pot_requires_integer_points(client):
    params = "match_id=points_validation&identity_type=anonymous&player_id=guestA&display_name=Breaker"
    with client.websocket_connect(f"/ws/room/?{params}") as ws:
        _ = ws.receive_text()
        ws.send_text(json.dumps({"action": "pot", "points": "7"}))
        err = json.loads(ws.receive_text())
        assert err["error"] == "Pot action requires integer 'points'."


def test_frame_conceded_broadcasts_completion_and_syncs(client, mock_rackup_client):
    params = "match_id=final_table&identity_type=verified&player_id=42&display_name=RonnieO"
    with client.websocket_connect(f"/ws/room/?{params}") as ws:
        _ = ws.receive_text()

        ws.send_text(json.dumps({"action": "frame_conceded"}))
        completion = json.loads(ws.receive_text())
        assert completion["type"] == "match_complete"
        assert completion["final_snapshot"]["match_id"] == "final_table"
        assert completion["final_snapshot"]["scores"]["user_42"] == 0

    mock_rackup_client.sync_final_frame.assert_called_once()
    sync_args = mock_rackup_client.sync_final_frame.call_args.args
    assert sync_args[0] == "final_table"
    assert sync_args[1]["match_id"] == "final_table"


def test_disconnect_notifies_remaining_opponent(client):
    p1_params = "match_id=disconnect_table&identity_type=anonymous&player_id=guest123&display_name=CasualRonnie"
    p2_params = "match_id=disconnect_table&identity_type=anonymous&player_id=guest789&display_name=CasualJudd"

    with client.websocket_connect(f"/ws/room/?{p2_params}") as ws2:
        _ = ws2.receive_text()

        with client.websocket_connect(f"/ws/room/?{p1_params}") as ws1:
            _ = ws1.receive_text()
            _ = ws2.receive_text()

        status_change = json.loads(ws2.receive_text())
        assert status_change["type"] == "player_status_change"
        assert status_change["key"] == "anon_guest123"
        assert status_change["status"] == "disconnected"
