# tests/test_matchroom.py
import json


def test_arcade_match_lifecycle(client):
    p1_params = "match_id=table_one&identity_type=anonymous&player_id=guest123&display_name=CasualRonnie"
    with client.websocket_connect(f"/ws/room/?{p1_params}") as ws1:
        # Consumes: Initial connection frame for Player 1
        _ = ws1.receive_text()

        p2_params = "match_id=table_one&identity_type=anonymous&player_id=guest789&display_name=CasualJudd"
        with client.websocket_connect(f"/ws/room/?{p2_params}") as ws2:
            # Consumes: Initial connection frame for Player 2
            _ = ws2.receive_text()

            # Flush: Player 1 now consumes the broadcast frame generated by Player 2 joining
            _ = ws1.receive_text()

            # Now both buffers are clean. Simulate Player 1 potting a Red.
            ws1.send_text(
                json.dumps(
                    {
                        "player": "player1",
                        "potted": True,
                        "potted_balls": ["red"],
                        "foul": 0,
                    }
                )
            )

            # Read the absolute fresh broadcast frames
            broadcast_p1 = json.loads(ws1.receive_text())
            assert broadcast_p1["scores"]["anon_guest123"] == 1
            assert broadcast_p1["current_break"] == 1


def test_successful_tournament_handshake(client, mock_rackup_client):
    params = "identity_type=verified&player_id=42&display_name=RonnieO&match_id=999"
    with client.websocket_connect(f"/ws/room/?{params}") as ws:
        data = json.loads(ws.receive_text())
        assert data["match_id"] == "999"
        assert data["current_turn"] == "user_42"

    # Verification is currently disabled in websocket.py
    mock_rackup_client.fetch_tournament_match.assert_not_called()


def test_unauthorized_player_is_currently_allowed_when_verification_disabled(client):
    # User 99 is currently accepted because verification is disabled.
    invalid_params = "identity_type=verified&player_id=99&display_name=Impostor&match_id=999"

    with client.websocket_connect(f"/ws/room/?{invalid_params}") as ws:
        data = json.loads(ws.receive_text())
        assert data["match_id"] == "999"
        assert data["current_turn"] == "user_99"


def test_reconnect_restores_existing_match_state(client):
    p1_params = "match_id=reconnect_table&identity_type=anonymous&player_id=guest123&display_name=CasualRonnie"

    with client.websocket_connect(f"/ws/room/?{p1_params}") as ws1:
        _ = ws1.receive_text()
        ws1.send_text(
            json.dumps(
                {
                    "player": "player1",
                    "potted": True,
                    "potted_balls": ["red"],
                    "foul": 0,
                }
            )
        )
        snapshot = json.loads(ws1.receive_text())
        assert snapshot["scores"]["anon_guest123"] == 1

    with client.websocket_connect(f"/ws/room/?{p1_params}") as ws1_reconnected:
        reconnect_snapshot = json.loads(ws1_reconnected.receive_text())
        assert reconnect_snapshot["scores"]["anon_guest123"] == 1


def test_invalid_action_messages_are_rejected(client):
    params = "match_id=validation_table&identity_type=anonymous&player_id=guestA&display_name=Breaker"
    with client.websocket_connect(f"/ws/room/?{params}") as ws:
        _ = ws.receive_text()
        ws.send_text(json.dumps({"action": "invalid_action"}))
        err = json.loads(ws.receive_text())
        assert "Unsupported action" in err["error"]


def test_turn_enforcement_blocks_out_of_turn_shots(client):
    p1_params = "match_id=turn_table&identity_type=anonymous&player_id=guest123&display_name=CasualRonnie"
    p2_params = "match_id=turn_table&identity_type=anonymous&player_id=guest789&display_name=CasualJudd"

    with client.websocket_connect(f"/ws/room/?{p1_params}") as ws1:
        _ = ws1.receive_text()

        with client.websocket_connect(f"/ws/room/?{p2_params}") as ws2:
            _ = ws2.receive_text()
            _ = ws1.receive_text()

            ws2.send_text(
                json.dumps(
                    {
                        "player": "player2",
                        "potted": True,
                        "potted_balls": ["black"],
                        "foul": 0,
                    }
                )
            )
            err = json.loads(ws2.receive_text())
            assert err["error"] == "It is not your turn to score."


def test_action_payload_with_points_is_rejected(client):
    params = "match_id=points_validation&identity_type=anonymous&player_id=guestA&display_name=Breaker"
    with client.websocket_connect(f"/ws/room/?{params}") as ws:
        _ = ws.receive_text()
        ws.send_text(json.dumps({"action": "pot", "points": "7"}))
        err = json.loads(ws.receive_text())
        assert err["error"].startswith("Unsupported action")


def test_disconnect_notifies_remaining_opponent(client):
    p1_params = "match_id=disconnect_table&identity_type=anonymous&player_id=guest123&display_name=CasualRonnie"
    p2_params = "match_id=disconnect_table&identity_type=anonymous&player_id=guest789&display_name=CasualJudd"

    with client.websocket_connect(f"/ws/room/?{p2_params}") as ws2:
        _ = ws2.receive_text()

        with client.websocket_connect(f"/ws/room/?{p1_params}") as ws1:
            _ = ws1.receive_text()
            _ = ws2.receive_text()

        status_change = json.loads(ws2.receive_text())
        assert status_change["type"] == "player_status_change"
        assert status_change["key"] == "anon_guest123"
        assert status_change["status"] == "disconnected"


def test_factual_shot_message_updates_table_and_can_be_undone(client):
    params = "match_id=factual_table&identity_type=anonymous&player_id=guest123&display_name=CasualRonnie"

    with client.websocket_connect(f"/ws/room/?{params}") as ws:
        initial = json.loads(ws.receive_text())
        assert initial["table"]["object_ball"] == "red"
        assert initial["points_remaining"] == 147
        assert initial["snooker_required"] == 0

        ws.send_text(
            json.dumps(
                {
                    "player": "player1",
                    "potted": True,
                    "potted_balls": ["red"],
                    "foul": 0,
                }
            )
        )

        update = json.loads(ws.receive_text())
        assert update["scores"]["anon_guest123"] == 1
        assert update["table"]["reds_remaining"] == 14
        assert update["table"]["object_ball"] == "colour"
        assert update["points_remaining"] == 146
        assert update["snooker_required"] == 0
        assert update["history_depth"] == 1

        ws.send_text(json.dumps({"undo": True}))
        undone = json.loads(ws.receive_text())
        assert undone["scores"]["anon_guest123"] == 0
        assert undone["table"]["reds_remaining"] == 15
        assert undone["table"]["object_ball"] == "red"
        assert undone["points_remaining"] == 147
        assert undone["snooker_required"] == 0
        assert undone["history_depth"] == 0
